#define MICROPY_HW_BOARD_NAME "ESP32C3 module"
#define MICROPY_HW_MCU_NAME "ESP32C3"

#define MICROPY_HW_I2C0_SCL (GPIO_NUM_4)
#define MICROPY_HW_I2C0_SDA (GPIO_NUM_5)

#define MICROPY_HW_SPI1_SCK (14)
#define MICROPY_HW_SPI1_MOSI (13)
#define MICROPY_HW_SPI1_MISO (12)

#define MICROPY_HW_SPI2_SCK (18)
#define MICROPY_HW_SPI2_MOSI (22)
#define MICROPY_HW_SPI2_MISO (19)


#define MICROPY_HW_ENABLE_SDCARD            (0)